# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "553af7442c947f41fef485eeadc9f387"
name = "aio-fns"
handle = "aio-fns"
application_url = "https://d4f1-2a09-bac5-d468-16d2-00-246-df.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-388e3623.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_order_edits,write_products"

[auth]
redirect_urls = [
  "https://d4f1-2a09-bac5-d468-16d2-00-246-df.ngrok-free.app/auth/callback",
  "https://d4f1-2a09-bac5-d468-16d2-00-246-df.ngrok-free.app/auth/shopify/callback",
  "https://d4f1-2a09-bac5-d468-16d2-00-246-df.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
